### ISSUE TITLE
can't build

### ISSUE THREAD

**Issue by arthurtsang** [calavera/docker-volume-keywhiz#1]
when i execute go get github.com/calavera/docker-volume-keywhiz, i get the following error
package github.com/docker/docker/pkg/sockets
    imports github.com/docker/docker/pkg/sockets
    imports github.com/docker/docker/pkg/sockets: cannot find package "github.com/docker/docker/pkg/sockets" in any of:
    /usr/lib/go/src/pkg/github.com/docker/docker/pkg/sockets (from $GOROOT)
    /home/arthur/go/src/github.com/docker/docker/pkg/sockets (from $GOPATH)
and when i check `docker/docker`.  they have removed `pkg/sockets` from master.  should this refer to the `release/v1.9` branch instead?

**Comment by arthurtsang** [comment]
after i checkout release/v1.9 for docker/docker in my GOPATH, i got this.

```
arthur@arthur-zbook:~/.gvm/pkgsets/go1.5/global/src/github.com/docker/docker$ git branch
* master
arthur@arthur-zbook:~/.gvm/pkgsets/go1.5/global/src/github.com/docker/docker$ git checkout release/v1.9
Branch release/v1.9 set up to track remote branch release/v1.9 from origin.
Switched to a new branch 'release/v1.9'
arthur@arthur-zbook:~/.gvm/pkgsets/go1.5/global/src/github.com/docker/docker$ cd 
arthur@arthur-zbook:~$ go get github.com/calavera/docker-volume-keywhiz
# github.com/calavera/dkvolume
.gvm/pkgsets/go1.5/global/src/github.com/calavera/dkvolume/tcp_listener.go:20: not enough arguments in call to sockets.NewTCPSocket
.gvm/pkgsets/go1.5/global/src/github.com/calavera/dkvolume/unix_listener.go:25: not enough arguments in call to sockets.NewUnixSocket
arthur@arthur-zbook:~$ go version
go version go1.5 linux/amd64

```

**Comment by arthurtsang** [comment]
i started keywhiz in a container `docker run -d -p 4444:4444 zuazo/keywhiz`
and got this

```
sudo ./docker-volume-keywhiz https://127.0.0.1:4444
Listening on /usr/share/docker/plugins/keywhiz.sock
listen unix /usr/share/docker/plugins/keywhiz.sock: bind: no such file or directory
```

**Comment by calavera** [comment]
#2 should have been fixed this. Thanks!
