### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by igorline** [calavera/docker-volume-keywhiz#4]
Hi! Totally new to go and I cannot install this.
Error i'm getting is 
`can't load package: /Users/igor/gocode/src/github.com/calavera/docker-volume-keywhiz/driver.go:14:2: import "github.com/square/keywhiz-fs" is a program, not an importable package`

Can you help?
Thanks 👍

**Comment by calavera** [comment]
It looks like they changed the whole package structure causing this to stop compiling:

https://github.com/square/keywhiz-fs/commit/4d18b0e5fed5e285f72cdd182f182f056f9b2d89

Probably, the easier solution is to vendor the latest good SHA that makes it compile, I'd start trying with the previous one to that change:

https://github.com/square/keywhiz-fs/tree/0369d465dac53848e6b76b1cc4d61c631cf9e7d0

**Comment by igorline** [comment]
I'll try it out!
Thanks
